config:
###############################
########## GERAL ##############
###############################
# tipo de ambiente esta informação deve ser editada pelo sistema
# 1-Produção 2-Homologação
    ambiente: 2
#esta variável contêm o nome do arquivo com todas as url dos webservices do sefaz
#incluindo a versao dos mesmos, pois alguns estados não estão utilizando as
#mesmas versões
    arquivoURLxml : /home/marcus/sites/nfephp2/config/nfe_ws2.xml
    arquivoURLxmlCTe : /home/marcus/sites/nfephp2/config/cte_ws1.xml
#Diretório onde serão mantidos os arquivos com as NFe em xml
#a partir deste diretório serão montados todos os subdiretórios do sistema
#de manipulação e armazenamento das NFe
    arquivosDir : /diretorio/para/grarvar/xmls
#URL base da API, passa a ser necessária em virtude do uso dos arquivos wsdl
#para acesso ao ambiente nacional
    baseurl : http://localhost:8000
#Versão em uso dos shemas utilizados para validação dos xmls
    schemes : PL_006s
    schemesCTe : PL_CTE_104
################################
####### EMPRESA EMITENTE #######
################################    
    empresa : TESTE
    UF: RJ
    cUF: 33
    cnpj : 99999999999999

################################
##### CERITIFICADO DIGITAL #####
################################
    certsDir : /home/marcus/sites/nfephp2/certs/
#Nome do certificado que deve ser colocado na pasta certs da API
    certName : certificado.pfx
#Senha da chave privada
    keyPass : 123456
#Senha de decriptaçao da chave, normalmente não é necessaria
    passPhrase : 

################################
############# DANFE ############
################################
#Configuração do DANFE
    danfeFormato : P
    danfePapel : A4 
    danfeCanhoto : 1
    danfeLogo : /caminho/para/logo
    danfeLogoPos : L
    danfeFonte : Times
    danfePrinter : hpteste

################################
############# EMAIL ############
################################
#Configuração do email
    mailAuth : 1
    mailFROM : nfe@seudominio.com.br
    mailHOST : smtp.seudominio.com.br
    mailUSER : nfe@seudominio.com.br
    mailPASS : suasenha
    mailPROTOCOL : 
    mailPORT : 25
    mailFROMmail : nfe@seudominio.com.br
    mailFROMname : NFe
    mailREPLYTOmail : nfe@seudominio.com.br
    mailREPLYTOname : NFe
    mailIMAPhost : mail.seudominio.com.br
    mailIMAPport : 143
    mailIMAPsecurity : tls
    mailIMAPnocerts : novalidate-cert
    mailIMAPbox : INBOX
    mailLayoutFile : layout da mensagem do email

################################
############# PROXY ############
################################
#Configuração de Proxy
    proxyIP :  
    proxyPORT :  
    proxyUSER :
    proxyPASS :  